"""
Django settings for configuracion_colegio project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

"""
Django settings for configuracion_colegio project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

# ---------------------------------------------------------
# BASE_DIR apunta al directorio raíz del proyecto (donde está manage.py)
# ---------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # PROYECTO_COLEGIO/

# Ruta a templates en frontend
FRONTEND_TEMPLATES_DIR = BASE_DIR / "frontend" / "templates"  # PROYECTO_COLEGIO/frontend/templates
FRONTEND_STATIC_DIR = BASE_DIR / "frontend" / "static"       # PROYECTO_COLEGIO/frontend/static

# ---------------------------------------------------------
# Ajustes básicos
# ---------------------------------------------------------
SECRET_KEY = 'django-insecure-h0e6w+5ap92zu+mx-sem8e1%9_fw**xqo3l)ufidzm8&e^nfhf'
DEBUG = True
ALLOWED_HOSTS = []

# ---------------------------------------------------------
# Aplicaciones
# ---------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tus apps
    'app_colegio',
]

# ---------------------------------------------------------
# Middleware
# ---------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'configuracion_colegio.urls'

# ---------------------------------------------------------
# Templates
# ---------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_TEMPLATES_DIR],   # carpeta frontend/templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',              # útil en desarrollo
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuracion_colegio.wsgi.application'

# ---------------------------------------------------------
# Base de datos (sqlite en la raíz del proyecto)
# ---------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------------------------------------
# Validación de contraseñas
# ---------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ---------------------------------------------------------
# Internacionalización
# ---------------------------------------------------------
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------
# Archivos estáticos
# ---------------------------------------------------------
STATIC_URL = '/static/'

# Rutas adicionales para buscar archivos estáticos en desarrollo
STATICFILES_DIRS = [
    FRONTEND_STATIC_DIR,  # PROYECTO_COLEGIO/frontend/static
]

# En producción debes configurar STATIC_ROOT y ejecutar collectstatic:
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# ---------------------------------------------------------
# Archivos media (si los necesitas)
# ---------------------------------------------------------
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------
# Otras opciones
# ---------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
